# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'adroit' do
  pod 'AppCenter/Crashes', '~> 1.11.0'
  pod 'AppCenter/Analytics', '~> 1.11.0'
  pod 'AppCenterReactNativeShared', '~> 1.10.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for adroit

  platform :ios, '9.0'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'adroitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'adroit-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for adroit-tvOS

  target 'adroit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
